# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf2e2e6a5cc351fd66bf82df44e16122432da5cfd6f7537f760b814e464eaddbcdb15aa6209810168efff6655694276199830c08d587adc1371c3178c9448aed

test:
  secret_key_base: 0e94d478e7d6a983d177113e1cdd5054a1890a50a2c348e5ded0a706f7822739cbe2c5aac77e783e2826b8091e96037383c1295fc7266254cdb57857ca3e2f5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
